// 데이터 파일로 배포할 테이블을 명시한다. 신규 테이블은 소유 DB를 먼저 결정한다.
export const DATA_TABLE_NAMES = [
  "benchmark_daily_values",
  "daily_selection_metric_coverage",
  "daily_selection_metrics",
  "dart_financial_filing_receipts",
  "facts",
  "fred_benchmark_coverage",
  "krx_daily_bars",
  "krx_non_trading_coverage",
  "krx_non_trading_days",
  "preparation_data_revision",
  "symbol_facts_state",
  "symbol_master_checkpoint_symbols",
  "symbol_master_checkpoints",
  "symbol_master_coverage",
  "symbol_master_events",
  "symbol_master_market_caps",
  "symbol_master_storage_state",
  "symbol_master_trading_days",
  "symbol_master_versions",
  "symbol_versions",
  "symbols"
] as const;

export const OPERATIONAL_TABLE_NAMES = [
  "dart_raw_api_snapshots",
  "audit_logs",
  "backtest_clone_batch_items",
  "backtest_clone_batches",
  "backtest_drawdown_points",
  "backtest_equity_points",
  "backtest_jobs",
  "backtest_metrics",
  "backtest_monthly_returns",
  "backtest_preparation_jobs",
  "backtest_runs",
  "backtest_trades",
  "backtest_validation_trials",
  "backtest_validations",
  "backtest_wizard_drafts",
  "data_sync_jobs",
  "external_api_daily_usage",
  "login_attempts",
  "notifications",
  "preparation_preview_cache",
  "preparation_wizard_references",
  "sessions",
  "symbol_coverage",
  "symbol_slices",
  "users"
] as const;
