---
- name: Deploy app release
  hosts: app
  gather_facts: false
  serial: 1
  any_errors_fatal: true
  roles:
    - role: app

- name: Deploy worker release
  hosts: worker
  gather_facts: false
  serial: 1
  any_errors_fatal: true
  roles:
    - role: worker
